# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18RzLMIKaufx75tE69L2yRrXbR4zX3i2-
"""

!git clone https://github.com/SonaliDasgupta/goodbooks-10k

import pandas as pd

!pip install fastai pytorch

ratings_df = pd.read_csv('goodbooks-10k/ratings.csv')

from fastai.collab import CollabDataBunch
from fastai.collab import collab_learner

import torch.optim as optim
from fastai.metrics import exp_rmspe
data = CollabDataBunch.from_df(ratings_df) #no test dataset here
wd = 1e-3
m = collab_learner(data, n_factors = 50, y_range = (1,5), metrics = [exp_rmspe])
#m.opt_fn = optim.Adam(params = m.parameters, lr = 0.5)
#choosing 50 factors as of now, might try with half the size of dataset later
#ratings go from 1 to 5 hence y_range

from fastai.train import lr_find
lr_find(m)
m.recorder.plot_metrics

m.recorder.plot()

m.opt = optim.Adam(params = m.model.parameters(), lr = 0.5)
#m.opt.mom = 0.9
m.fit(3, lr = 0.5, wd = 1e-5) #PULL CODE IN SPYDER  AND SEE OPTIM WRAPPER USAGE , TRY WITH ADAM LATER AND ALSO WEIGHT DECAY AND MOMENTUM
#TRY WITH BOTH ADAM AND SGD

#with SGD optimization
m1 = collab_learner(data, n_factors = 50, y_range = (1,5), metrics = [exp_rmspe])
m1.opt = optim.SGD(params = m1.model.parameters(), lr = 0.5, momentum = 0.9)
m1.opt.mom = 0.9
m1.fit(3, lr = 0.05)

#SGD performs way better
#TRY ONCE WITH SAME WEiGHT DECAY

#1.  interpret embeddings
#2. Create columnar model using the metatdata, and compare the 2 models on a metric

m1.model.i_weight #analyzing movie categories
from sklearn.decomposition import PCA